USE [master]
GO

/****** Object:  Database [SAMPLEDB]    Script Date: 24-03-2025 16:59:32 ******/
CREATE DATABASE [SAMPLEDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SAMPLEDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SAMPLEDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SAMPLEDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SAMPLEDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SAMPLEDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SAMPLEDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SAMPLEDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SAMPLEDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SAMPLEDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SAMPLEDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SAMPLEDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SAMPLEDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SAMPLEDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SAMPLEDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SAMPLEDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SAMPLEDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SAMPLEDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SAMPLEDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SAMPLEDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SAMPLEDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SAMPLEDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SAMPLEDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SAMPLEDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SAMPLEDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SAMPLEDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SAMPLEDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SAMPLEDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SAMPLEDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SAMPLEDB] SET  MULTI_USER 
GO

ALTER DATABASE [SAMPLEDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SAMPLEDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SAMPLEDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SAMPLEDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SAMPLEDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SAMPLEDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SAMPLEDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [SAMPLEDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SAMPLEDB] SET  READ_WRITE 
GO


